### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by SylvanFranklin** [rjain37/typstracer#4]
### Problem Title

Missing docs

### Problem Description

How do I run this app? The readme does not say and I see that is has javascript and Typst?

### Typst Code

Why does this issue need Typst code?

**Comment by rjain37** [comment]
Hi! This issue template is to add new problems to the game. Any actual issues you have can be addressed in an untemplated issues.

But to answer your question, you can download it and run `node server`.

Though, you could also just go to the website.

**Comment by SylvanFranklin** [comment]
Oh okay makes sense, I think you could prolly just say that in the readme since it is pretty likely that people will get that, but it could just be vanilla js or an alternate runtime like bun or deno
